### ISSUE TITLE
Suggest: remove `doc/sep23`

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/bianca_workshop#14]
Currently, there is a folder called `doc/sep23` that contains old files from the -I guess- september 2023 course.

I suggest to remove those old files, as we use a versioning control system, together with regular releases.

**Comment by richelbilderbeek** [comment]
We have [11 releases](https://github.com/UPPMAX/bianca_workshop/releases)  at the moment, so one can easily go back in time :+1:

Do I need to show how to browse a GitHub repo of an earlier release? I'd be happy to!

**Comment by bclaremar** [comment]
DONE
Also deleted apr24
