### ISSUE TITLE
Integrate `docs/extra/rpackages_copy.md` into docs and this course!

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/bianca_workshop#15]
Currently, there is a file called `docs/extra/rpackages_copy.md` that contains an older version of -I guess- `doc/extra/rpackages.md`.

I suggest to remove that old file, as we use a versioning control system, together with regular releases.

**Comment by dianaiusan** [comment]
I agree. I'll fix it after the workshop.

**Comment by bclaremar** [comment]
No!
This should be integrated with time into docs and this course!
Did however forget it until now!
I'll take the issue!

**Comment by bclaremar** [comment]
made [r_packages_bianca.md](https://github.com/UPPMAX/UPPMAX-documentation/blob/main/docs/software/r_packages_bianca.md)

**Comment by bclaremar** [comment]
interestingly I found this page that will change my present lesson!
https://docs.uppmax.uu.se/software/create_singularity_container_for_r_package/
Thank you Richel!
