### ISSUE TITLE
Update schedule?

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/bianca_workshop#20]
Currently [https://uppmax.github.io/bianca_workshop/intermediate/intro/](https://uppmax.github.io/bianca_workshop/intermediate/intro/) contains the schedule of the previous iteration of the course and a proposed newer schedule of the coming course.

I suggest to use the proposed schedule and remove the older one. I volunteer to do so, so go ahead and assign me when there is agreement here.

**Comment by bclaremar** [comment]
Marcus will not have the sens part. emailing Lars to hear his opinion

**Comment by richelbilderbeek** [comment]
I asked Lars too now before reading this :-)

**Comment by richelbilderbeek** [comment]
Lars accepted, new schedule is accepted, old one is removed.

Closing this Issue!
