### ISSUE TITLE
Evaluate Bianca Intermediate course yes/no?

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/bianca_workshop#28]
Last 'Intro to Bianca' course was not evaluated. 

Maybe we do not think it is important?

This Issue is intended to help us remind to decide on evaluate on this course and if we pick to do so, do so :-)

**Comment by bclaremar** [comment]
Do as last time directly in hackmd??

**Comment by bclaremar** [comment]
We all agreed on this
