### ISSUE TITLE
Basic Bianca course: box in introduction about copy-pasting in thinlinc

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/bianca_workshop#30]
list of copy-paste commands for Win/Mac in ThinLinc + [screenshot of copy-paste area](https://uppmax.github.io/bianca_workshop/img/copy_paste.PNG)
Place: Introduction

**Comment by bclaremar** [comment]
also linux commands that people may easily forget
- which ones?
tab complete

**Comment by richelbilderbeek** [comment]
@bclaremar thanks, I will happily take a look. 

Which URL is this about? Is it https://uppmax.github.io/bianca_workshop/login_bianca/ ? 

If I know, I will take a look.

**Comment by bclaremar** [comment]
It's about the https://uppmax.github.io/bianca_workshop/intro/ page

- Also make sure they log in already in this session!?

- A link to https://uppmax.github.io/bianca_workshop/commandline/ would probably do for a reminder of the linux commands.
- Perhaps add in that file
    - tab complete 
    - the copy-pasting in ThinLinc and between TL and local computer part

**Comment by richelbilderbeek** [comment]
Ah, it is the basic course (not the one we teach tomorrow), thanks!

> Also make sure they log in already in this session!?

For the basic course, there is time in the schedule (at https://uppmax.github.io/bianca_workshop/intro ) to login, see https://uppmax.github.io/bianca_workshop/login_bianca/ . The page where the learners learn to login ( https://uppmax.github.io/bianca_workshop/login_bianca/ ) forwards the learners to the UPPMAX documentation, at http://docs.uppmax.uu.se/getting_started/login_bianca/ . I agree discussing the ThinLinc copy-paste box there is a good idea!

> A link to https://uppmax.github.io/bianca_workshop/commandline/ would probably do for a reminder of the linux commands.

I feel we do not need to link from the introduction page (  https://uppmax.github.io/bianca_workshop/intro/  ) , as the command-line has a dedicated session at https://uppmax.github.io/bianca_workshop/commandline/ . 

> Perhaps add in that file (commandline.md)
> - tab complete
> - the copy-pasting in ThinLinc and between TL and local computer part

I think these are good ideas for https://uppmax.github.io/bianca_workshop/commandline/ ! I'll check the next time we do a Bianca basic course again

**Comment by richelbilderbeek** [comment]
Assuming I am teaching that part of the next Basic Bianca course, I will assign myself to do so :-)

**Comment by bclaremar** [comment]
sorry sorry, I meant the /intermediate/intro.md, pointing with "fresh-up" links to the basics of the intro workshop

**Comment by bclaremar** [comment]
but it includes adding the stuff I mentioned into the basics of command line the first workshop

**Comment by richelbilderbeek** [comment]
Ah, @bclaremar I just happended to so: I thought it was a good idea to do it here too :-)

I thanked you even in the commit at https://github.com/UPPMAX/bianca_workshop/commit/ddade8453035eb879fc1c1104ca6cb3acc9c6da4 :+1:

I will leave this Issue open, so it is done for the Basic course too!

**Comment by richelbilderbeek** [comment]
@bclaremar:

> Also make sure they log in already in this session!?

I will.

**Comment by richelbilderbeek** [comment]
Ah, this is already done. Thanks!

![Screenshot from 2024-05-24 06-33-38](https://github.com/UPPMAX/bianca_workshop/assets/2098230/833474b6-bea2-4c53-9789-e63b97611a15)

Go ahead and unassign me next time and close the Issue :+1:
