### ISSUE TITLE
Should IDEs focus on IDEs and not virtual environments?

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/bianca_workshop#31]
@bclaremar I've seen [this commit](https://github.com/UPPMAX/bianca_workshop/commit/146c39dac6475f677aac9355a9a1cc0f5495ab16) and I wonder about this line at [IDEs: exercise 1: start the favorite IDE](https://uppmax.github.io/bianca_workshop/intermediate/ides/#exercise-1-start-the-favorite-ide):

> For Jupyter, you can skip the venv step, but please read it!

I feel that letting learners read about virtual environments during a session on starting an IDE is outside of the purpose of the session.

I suggest to remove this line, to prevent learners from following these instructions and having no time left to actually start an IDE.

Would you agree?

**Comment by bclaremar** [comment]
Update:
For Jupyter, you can skip the venv step!

**Comment by richelbilderbeek** [comment]
@bclaremar Awesome, thanks!
