### ISSUE TITLE
Would you enjoy a guide how to run Jupyter on Bianca?

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/bianca_workshop#32]
Currently, two out of three IDEs on Bianca has a step-by-step guide:

- http://docs.uppmax.uu.se/cluster_guides/rstudio_on_bianca/
- http://docs.uppmax.uu.se/cluster_guides/vscodium_on_bianca/

Would it be useful to create such a page for Jupyter? If yes, I volunteer to do so.

I ask @bclaremar as he'll be teaching it tomorrow and may not have time to do so.

A no or 'it is too late now' is perfectly fine too :-)

**Comment by bclaremar** [comment]
Nothing different on Bianca. Seems to work well to me in ThinLinc (XFCE).
But I agree that it looks nice to have a Bianca version. 

Oh, I have an idea:
- copy software/jupyter to cluster_guides/jupiter_on_bianca
- add the parts in https://uppmax.github.io/R-python-julia-HPC/python/jupyter.html#on-own-computer to the ordinary version in software.

**Comment by bclaremar** [comment]
I'll make the bianca copy now, at least.
And change link from IDEs on cluster_guides/bianca and the course page for IDEs

**Comment by richelbilderbeek** [comment]
Awesome! Good luck!

**Comment by bclaremar** [comment]
- [ ] cluster_guides/jupyter_on_bianca.md file
- [ ] update of software/jupyter with temporary link to course material about graphics own computer (rackham)
- [ ] create issue to integrate the rst code from course (https://uppmax.github.io/R-python-julia-HPC/python/jupyter.html#on-own-computer) to md in docs repo
