### ISSUE TITLE
Suggestion: move compute-node-required exercises to slurm session instead

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/bianca_workshop#37]
In https://uppmax.github.io/bianca_workshop/modules1/

@bclaremar  would like to take over:
- Hands on: Running R within RStudio, use ggplot2 from R_packages/4.1.1
    - we should teach them to never run rstudio on login node

- Hands on: Processing a BAM file to a VCF using GATK, and annotating the variants with snpEff
     - you state it should be run on compute node
     - let's then do it after they had the slurm introduction!

Can you come up with lighter alternatives possible on the login node, to replace the ones I steal?
- perhaps combining steps from earlier sessions?

**Comment by bclaremar** [comment]
Ha!

I did this already a year ago.

Thinking of having both as extra hard. One in interactive and one in batch to show the benefits in automatize things.

I believe that automatization is part of the intro course to avoid missing steps. A strong benefit of well structured batch jobs!

**Comment by richelbilderbeek** [comment]
Great, done is done :+1: !

**Comment by richelbilderbeek** [comment]
> But do you agree to revise your exercises to something that can be run on the login node

Ah, now I see you point (if I read something is done, I will rarely read on, as I will assume it is ... well ... done :+1). Sure, I will remove heavy exercises if I have these at all. I'll assign myself!

**Comment by richelbilderbeek** [comment]
All my exercises can safely be run on the login node :+1:

My work is done here and I will unassign :-)
