### ISSUE TITLE
Fixing schedule according to matrix chat

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/bianca_workshop#43]

**Comment by richelbilderbeek** [comment]
Done! Twice to be exact :-)

**Comment by richelbilderbeek** [comment]
It was only some spaces that gave a conflict. No need to have invited me; I prefer doing stuff over waiting :rocket:

**Comment by richelbilderbeek** [comment]
Nah, happy to see you were even faster than me :+1:
