### ISSUE TITLE
Maja is replacing Bianca soon - at what level shall this be communicated in intro course

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/bianca_workshop#44]
example 1
- in intro have a box where we state that:
   -  we think that most things will be similar in new system as in course, just different name

**Comment by richelbilderbeek** [comment]
I will make sure the learners can have seen it in the UPPMAX documentation. A (stub) page on Maja is already there :+1:

**Comment by richelbilderbeek** [comment]
Among others, it is written down [at the Bianca page of the UPPMAX docs](https://docs.uppmax.uu.se/cluster_guides/bianca/)

**Comment by richelbilderbeek** [comment]
I feel this is good enough for now. There will be questions during the course. Besides that, I feel I've done this Issue and will unassign :+1:
