### ISSUE TITLE
Is overview.md even used? we both try to modify it but now I don't see it in the rendered web tree!

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/bianca_workshop#45]

**Comment by richelbilderbeek** [comment]
It is indeed never used. I put it at the `mkdocs.yaml` at the session 'Extra', which is part of the Intermediate course.

- Would the file be deleted, I'd be happy
- Would the file find a better home, I'd be happy too

**Comment by bclaremar** [comment]
OK, Let's keep it there for now!

I'll reopen the md check for it

Seems that you already made the fixes to it
