### ISSUE TITLE
Fresh copy of the HackMD created

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/bianca_workshop#48]
https://hackmd.io/@UPPMAX/bianca_sep2024_QaA/edit

**Comment by bclaremar** [comment]
Interesting discussions but will just keep the first one (your example)
The old QaA document is still in the UPPMAX HackMD repo if we want to paste some learnings!

**Comment by bclaremar** [comment]
https://hackmd.io/@UPPMAX/Bianca_Intro_QaA is the link to that one

**Comment by richelbilderbeek** [comment]
The old HackMD was already copy-pasted to [https://github.com/UPPMAX/bianca_workshop/blob/main/shared_documents/20240419.md](https://github.com/UPPMAX/bianca_workshop/blob/main/shared_documents/20240419.md) :+1:

**Comment by bclaremar** [comment]
Rather clean now
