### ISSUE TITLE
Remove files that serve as a backup

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/bianca_workshop#56]
Currently, there are three files in `docs/intermediate` that seem to serve like a backup of sorts:

```bash
richel@richel-N141CU:~/GitHubs/bianca_workshop/docs/intermediate$ tree
.
├── complex_jobs.md
├── ...
├── intro.md
├── overview2.md <------------------------- should be the new overview.md?
├── overview.md <------------------------- old?
├── practicalities2.md <------------------------- should be practicalities.md?
```

As we use `git` for version control, as was as there are regular releases, these files can be either removed, renamed of merged.

I feel it is quite annoying to maintain old files for broken links and sorts.

I do feel that the following actions would fix this:
- overview.md: delete
- overview2.md: rename to overview2.md
- practicalities2.md: rename to practicalities.md

**Comment by richelbilderbeek** [comment]
![Screenshot from 2024-12-04 13-23-46](https://github.com/user-attachments/assets/3a19917d-e41e-4ea4-b0ab-c9e4e162c5b0)

Ah, it is `overview.md` that is newer.

So:

- overview.md: keep
- overview2.md: delete
- practicalities2.md: rename to practicalities.md

**Comment by bclaremar** [comment]
Seems this is done!
